### PR TITLE
Add Edge to Browser History, update artifacts

### PR DESCRIPTION
**Pull request by tobraha**
Many of the Chrome artifacts are outdated. This updates those artifacts and also adds in artifacts for Microsoft Edge.

### CODE REVIEW

**Comment by tobraha** [comment]
Converting to draft because I just realized there's no reason to take out the old artifacts :upside_down_face: 

I'll take another stab at this after I get some sleep.

**Comment by Schamper** [comment]
Hi @tobraha, no problem, just give a ping when it's good to go!

**Comment by tobraha** [comment]
> @tobraha thank you for your contribution! As this is your first code contribution, please read the following Contributor License Agreement (CLA). If you agree with the CLA, please reply with the following information:
> 
> ```
> @DissectBot agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@DissectBot agree

**Comment by tobraha** [comment]
> Hi @tobraha, no problem, just give a ping when it's good to go!

Hey @Schamper - that should do it. Build seems to be successful for me on Linux & Python 3.9.

**Comment by Schamper** [comment]
Can you fix the linting error? Otherwise good to go!

**Review by Schamper — APPROVED** [review]

**Comment by Schamper** [comment]
> There we are - linting passes for my with Python 3.9.5

Thanks!

**Pull request merged**
